# SPDX-FileCopyrightText: Idiap Research Institute
#
# SPDX-License-Identifier: CC0-1.0

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.0
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-case-conflict
    - id: debug-statements
    - id: check-added-large-files
    - id: check-docstring-first
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
    - id: mypy
      args: [--strict]
      additional_dependencies:
        - "librosa"
        - "matplotlib"
        - "numpy"
        - "phonetisaurus"
        - "pytest"
        - "scipy"
- repo: https://github.com/fsfe/reuse-tool
  rev: v2.1.0
  hooks:
    - id: reuse
