# SPDX-FileCopyrightText: Idiap Research Institute
#
# SPDX-License-Identifier: CC0-1.0

name: unit-tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run coverage run
      - run: poetry run coverage report
